# Generated by Django 6.0 on 2026-01-19 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_favorite_book_rating_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Атауы')),
                ('scroll_position', models.FloatField(verbose_name='Прокрутка позициясы (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Күні')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бетбелгі',
                'verbose_name_plural': 'Бетбелгілер',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReadingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Күн')),
                ('seconds_read', models.IntegerField(default=0, verbose_name='Оқылған секундтар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_stats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оқу статистикасы',
                'verbose_name_plural': 'Оқу статистикасы',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
